### ISSUE TITLE
UNO Type Selector not working

### ISSUE THREAD

**Issue by smehrbrodt** [LibreOffice/loeclipse#22]
Not showing any types

**Comment by smehrbrodt** [comment]
Investigated a little bit on this:

`TypesGetter.java:252`
fails with 
`com.sun.star.registry.InvalidRegistryException: com.sun.star.registry.SimpleRegistry.open(file:///C:/Program%20Files/LibreOffice%205/program/types.rdb): underlying Registry::open/create() = 7`

with the error code 7 meaning 

>  registry is in an invalid state or the registry does not point to a valid registry data file. (http://opengrok.libreoffice.org/xref/core/include/registry/regtype.h#102)

Although the URL is correct.

**Comment by XavierMarchena** [comment]
This is what i get on my machine:

!ENTRY org.libreoffice.ide.eclipse.core 4 4 2018-02-15 14:11:26.882
!MESSAGE Failed to get the types from the office
!STACK 0
com.sun.star.registry.InvalidRegistryException: com.sun.star.registry.SimpleRegistry.open(file:///usr/lib/libreoffice/program/types.rdb): underlying Registry::open/create() = 7
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:160)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:124)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:319)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:288)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:80)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:617)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:144)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy33.open(Unknown Source)
	at org.libreoffice.ide.eclipse.core.internal.office.TypesGetter.getTypesFromRegistry(Unknown Source)
	at org.libreoffice.ide.eclipse.core.internal.office.TypesGetter.queryTypes(Unknown Source)
	at org.libreoffice.ide.eclipse.core.internal.office.TypesGetter.getTypes(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.libreoffice.ide.eclipse.core.office.TypesGetter.getTypes(Unknown Source)
	at org.libreoffice.ide.eclipse.core.unotypebrowser.UnoTypeProvider$UnoTypesGetterThread.run(Unknown Source)

!ENTRY org.libreoffice.ide.eclipse.core 0 0 2018-02-15 14:11:26.883
!MESSAGE Types fetched

**Comment by shobhanmandal** [comment]
I believe this is because, the types.rdb file which is being placed in the current LibreOffice Installation is having a different format than earlier: http://document-foundation-mail-archive.969070.n3.nabble.com/lo-4-2-regview-fails-to-show-rdb-files-td4087496.html
