### ISSUE TITLE
SWTException below ChoiceRow.removeAll

### ISSUE THREAD

**Issue by smehrbrodt** [LibreOffice/loeclipse#60]
```
Bundle: org.eclipse.ui 3.109.0.v20170411-1742
Message: Unhandled event loop exception
Exception:
org.eclipse.swt.SWTException: Widget is disposed
    at org.eclipse.swt.SWT.error(SWT.java:4533)
    at org.eclipse.swt.SWT.error(SWT.java:4448)
    at org.eclipse.swt.SWT.error(SWT.java:4419)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:487)
    at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:424)
    at org.eclipse.swt.widgets.Combo.removeAll(Combo.java:1768)
    at org.libreoffice.ide.eclipse.core.gui.rows.ChoiceRow.removeAll(null:-1)
    at org.libreoffice.ide.eclipse.core.gui.rows.AbstractConfigRow.fillRow(null:-1)
    at org.libreoffice.ide.eclipse.core.gui.rows.AbstractConfigRow.access$100(null:-1)
    at org.libreoffice.ide.eclipse.core.gui.rows.AbstractConfigRow$ConfigListener.ConfigAdded(null:-1)
    at org.libreoffice.ide.eclipse.core.model.OOoContainer.fireOOoAdded(null:-1)
    at org.libreoffice.ide.eclipse.core.model.OOoContainer.addOOo(null:-1)
    at org.libreoffice.ide.eclipse.core.gui.OOoTable.addLine(null:-1)
    at org.libreoffice.ide.eclipse.core.gui.AbstractTable$2.widgetSelected(null:-1)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
```

Reported by automated error reporting: https://aer.ctrlflow.com/loeclipse/reviewers#!/problems/5a8f0747e4b037c4757ec133

**Comment by viragumathe5** [comment]
Will anybody please elaborate the issue 
Also link is showing error 502 bad gateway

**Comment by smehrbrodt** [comment]
What do you need to know? There is no additional information under that link.
